spring.application.name=ap-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/ap_tracker
spring.datasource.username=jashawnrogers
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Defines how the database schema changes at runtime (update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=update

# Optional: Formats and logs SQL statements in the console (useful for development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Explicitly enforces a target schema if not using 'public'
# spring.jpa.properties.hibernate.default_schema=my_schema
